import test from 'node:test';
import assert from 'node:assert/strict';
import { SCENES, TOTAL, createGame, decisionState, hashChoice, lockChoice, playRound, practiceDecision, publicGame, roleAt } from '../game.mjs';

test('scenes loop forever and role switches every five rounds',()=>{const game=createGame('practice');assert.equal(SCENES.length,10);assert.equal(roleAt(0),'evader');assert.equal(roleAt(4),'evader');assert.equal(roleAt(5),'catcher');assert.equal(roleAt(9),'catcher');assert.equal(roleAt(10),'evader');for(let i=0;i<TOTAL+2;i++){const locked=lockChoice(game,{choice:i%2?'left':'right',model:'test',elapsedMs:0});assert.equal(game.phase,'ready');const result=playRound(game,{round:i,choice:i%2?'right':'left',commitment:locked});assert.equal(result.round,i+1);assert.equal(result.scene,SCENES[i%SCENES.length].id);assert.equal(game.phase,'preparing');}assert.equal(game.round,TOTAL+2);});

test('commitment is deterministic and cannot reveal or reuse a choice',()=>{const game=createGame();const commitment=lockChoice(game,{choice:'left',model:'fixture',elapsedMs:1});assert.match(commitment,/^[a-f0-9]{64}$/);assert.equal(commitment,hashChoice(game.id,0,'left',game.pending.salt));assert.throws(()=>playRound(game,{round:0,choice:'right',commitment:'wrong'}),/凭证/);const result=playRound(game,{round:0,choice:'right',commitment});assert.equal(result.playerWon,true);assert.throws(()=>playRound(game,{round:0,choice:'left',commitment}),/回合/);});

test('evader scores when choices differ and catcher scores when choices match',()=>{const game=createGame();lockChoice(game,{choice:'left',model:'test',elapsedMs:0});const first=playRound(game,{round:0,choice:'right',commitment:game.pending.commitment});assert.equal(first.playerWon,true);for(let i=1;i<5;i++){lockChoice(game,{choice:'left',model:'test',elapsedMs:0});playRound(game,{round:i,choice:'right',commitment:game.pending.commitment});}assert.equal(game.round,5);lockChoice(game,{choice:'right',model:'test',elapsedMs:0});const result=playRound(game,{round:5,choice:'right',commitment:game.pending.commitment});assert.equal(result.playerWon,true);});

test('decision state contains history only and no future/private choice',()=>{const game=createGame('jev');lockChoice(game,{choice:'left',model:'fixture',elapsedMs:0});const state=decisionState(game);assert.equal(state.history.length,0);assert.ok(!JSON.stringify(state).includes(game.pending.salt));const view=publicGame(game);assert.equal(view.commitment,game.pending.commitment);assert.ok(!('pending' in view));});

test('public scene catalog keeps the English labels and endless marker',()=>{const view=publicGame(createGame());assert.equal(view.totalRounds,null);assert.equal(view.scenes.length,TOTAL);assert.equal(view.scenes[0].en,'THE MISTY WOODS');});

test('endless game keeps accepting rounds and local bot remains explicit',()=>{const game=createGame();for(let i=0;i<TOTAL*3;i++){lockChoice(game,practiceDecision(game,()=>.3));playRound(game,{round:i,choice:i%2?'left':'right',commitment:game.pending.commitment});assert.notEqual(game.phase,'finished');}assert.equal(game.phase,'preparing');assert.equal(game.round,TOTAL*3);assert.equal(game.playerScore+game.rivalScore,TOTAL*3*100);assert.equal(practiceDecision(createGame()).model,'本地习惯机器人');});
